### ISSUE TITLE
Fails with "Couldn't run 'screen'" if tmux is not installed.

### ISSUE THREAD

**Issue by daniel-nth** [niemeyer/hsandbox#22]
Says
> error: Couldn't run 'screen'.  Is it installed?  

but actually looks for tmux.

**Comment by matrinox** [comment]
+1 Thanks, installing tmux fixed it. Need better error for this

**Comment by niemeyer** [comment]
Sorry, the terminal session management program changed from "screen" to "tmux" a while ago, and the error message was out of date.

**Comment by matrinox** [comment]
thanks that was helpful @niemeyer
